void h(){
    case1:
    "inline//\\extern";
    case2:
    "const||char";
    case3:
    "BigInt&&Float";
    case4:
    "const\\extern";
    case5:
    "char&&inline";
    casF6:
    "Float//BigInt";
    case7:
    "char\\\\&extern";
    case8:
    "const&////inline";
    case9:
    "BigInt&\\//&Float";
}
